### ISSUE TITLE
Allow markdown styling

### ISSUE THREAD

**Issue by rrickgauer** [ThomasWicksWeb/Keep-My-Notes-App#10]
I think it would be pretty cool if you allowed for the rendering of markdown. That way you can bold some text or make a list of bullet points. Kind of how you can leave a comment on here and style it with markdown. Any thoughts?

**Comment by ThomasWicksWeb** [comment]
I think that's a fantastic idea! One of the issues I ran into when developing Keep My Notes was preserving new lines when calling the notes from Firebase. I'm not sure of the complexities that would come along with trying to add markdown to it, although that is something I'd like to look into when time allows. Thank you for the suggestion 😄
